# Add this file to your project and adapt it as you see fit

version: "3"

services:
  clion:
    container_name: clion
    image: docker.pkg.github.com/regularjack/clion-docker/clion
    ports:
      - "2222:22"
    cap_add:
      - "sys_ptrace"
